create table USERS
(
  dni          VARCHAR2(10) not null,
  fullname     VARCHAR2(80) not null,
  email        VARCHAR2(50) not null unique,
  password     VARCHAR2(200) not null,
  phone        VARCHAR2(10) unique,
  home_address VARCHAR2(100)
);

create table ALARMS
(
  user_dni    VARCHAR2(10) not null,
  type        VARCHAR2(30) not null,
  description VARCHAR2(100) not null,
  issued_at   TIMESTAMP(6) not null
);

create table ORGANIZATIONS
(
  name_org    VARCHAR2(100) not null,
  phone_org   VARCHAR2(10) not null,
  email_org   VARCHAR2(50) not null,
  address_org VARCHAR2(100) not null,
  user_dni    VARCHAR2(10) not null
);

create table EVENTS
(
  id               NUMBER(4) generated by default as identity,
  user_dni         VARCHAR2(10) not null,
  name             VARCHAR2(80) not null,
  description      VARCHAR2(250) not null,
  date_start       TIMESTAMP(6) not null,
  duration         VARCHAR2(5) not null,
  num_attendees    NUMBER(7) not null,
  capacity_allowed NUMBER(4,4) not null,
  type             VARCHAR2(30),
  state            VARCHAR2(20) default 'ACTIVE'
);

create table PLACES
(
  id           NUMBER(4) generated by default as identity,
  event_id     NUMBER(4) not null,
  name         VARCHAR2(50) not null,
  address      VARCHAR2(100) not null,
  type         VARCHAR2(30) not null,
  capacity_max NUMBER(7) not null
);

create table UNSUBSCRIBED_EVENTS
(
  event_id NUMBER(4) not null,
  reason   VARCHAR2(200) not null
);

create table PLANS
(
  id        NUMBER(4) generated by default as identity,
  name_plan VARCHAR2(20) not null,
  price     NUMBER(5) not null
);

create table AGREEMENTS
(
  id         NUMBER(4) generated by default as identity,
  date_issue DATE not null,
  user_dni   VARCHAR2(10) not null,
  plan_id    NUMBER(4) not null,
  event_id   NUMBER(4) not null
);

create table PILOTS
(
  dni          VARCHAR2(10) not null,
  fullname     VARCHAR2(80) not null,
  email        VARCHAR2(50) not null unique,
  phone        VARCHAR2(10) unique,
  home_address VARCHAR2(100),
  experience   VARCHAR2(300) not null,
  path_img     VARCHAR2(100)
);

create table DRONES
(
  id          NUMBER(4) generated by default as identity,
  brand       VARCHAR2(100) not null,
  description VARCHAR2(200) not null,
  pilot_dni   VARCHAR2(10) not null,
  path_img    VARCHAR2(100)
);

create table ADMINISTRATORS
(
  name     VARCHAR2(100) not null,
  email    VARCHAR2(50) not null,
  password VARCHAR2(200) not null,
  dni      VARCHAR2(10) not null
);