-- CREATE ALL TABLES OF DRONESOLUTION SCHEME

CREATE TABLE users(
  dni VARCHAR2(10) NOT NULL,
  fullname VARCHAR2(80) NOT NULL,
  email VARCHAR2(50) NOT NULL UNIQUE,
  password VARCHAR2(200) NOT NULL,
  phone VARCHAR2(10) UNIQUE,
  home_address VARCHAR2(100),
) TABLESPACE ts_dronesolution;

CREATE TABLE agreements(
  id NUMBER(4) GENERATEDBY DEFAULT AS IDENTITY,
  date DATE NOT NULL,
  user_dni VARCHAR2(10),
  plan VARCHAR2(20) NOT NULL,
  event_id NUMBER(4)
) TABLESPACE ts_dronesolution;

CREATE TABLE events(
  id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY,
  user_dni VARCHAR2(10) NOT NULL,
  name VARCHAR2(80) NOT NULL,
  description VARCHAR2(250) NOT NULL,
  date_start TIMESTAMP NOT NULL,
  duration VARCHAR2(5) NOT NULL,
  num_attendees NUMBER NOT NULL,
  capacity_allowed NUMBER NOT NULL,
  type VARCHAR2(20),
  state VARCHAR2(20) DEFAULT 'ACTIVE',
  -- PRIMARY KEY(id),
  -- FOREIGN KEY(user_dni) REFERENCES users(dni)
) TABLESPACE ts_dronesolution;

CREATE TABLE places(
  id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY,
  event_id NUMBER(4) NOT NULL,
  name VARCHAR2(50) NOT NULL,
  address VARCHAR2(50) NOT NULL,
  type VARCHAR2(25) NOT NULL,
  capacity_max NUMBER(7) NOT NULL
) TABLESPACE ts_dronesolution;

CREATE TABLE alarms(
  user_dni VARCHAR2(10) NOT NULL,
  type VARCHAR2(20) NOT NULL,
  description VARCHAR2(50) NOT NULL,
  issued_at TIMESTAMP(2) NOT NULL
) TABLESPACE ts_dronesolution;

CREATE TABLE unsubscribed_events(
	event_id NUMBER(4,0),
	reason VARCHAR2(100)
) TABLESPACE ts_dronesolution;